### ISSUE TITLE
Code structure seems wrong, testing is not possible

### ISSUE THREAD

**Issue by dJani97** [udacity/nd940-android-kotlin-c4-starter#1]
There seem to be a structural issue with this starter code:

In the related course section, `TaskDataSource` is an interface, which is implemented by both `LocalDataSource` and `RemoteDataSource` classes.

Then, using composition, these two `DataSources` are included in the `Repository` as dependencies.

So in the course, when testing this `Repository`, the instructor swaps out these `DataSource` implementations to _Fake_ ones.

In this starter code, `LocalDataSource` does not exist, and instead the `Repository` itself takes it's place, and implements the `DataSource` interface, making it impossible to swap out it's dependencies to Fake ones. One very important layer of abstraction is simply left out.

This way, I do not understand how we should approach testing using the `FakeDataSource` class.

Please check if my standpoint is valid, and if it is, correct the starter code.

**Comment by mohamed-habib** [comment]
In the course, the Repository existed to interact with both the `LocalDataSource` and `RemoteDataSource`, which is not needed in our project otherwise it will be only just calling the `LocalDataSource` methods.
Here in this project, the `RemindersLocalRepository` acts as the `LocalDataSource`, So just as the `FakeDataSource` in the course implements `TasksDataSource` interface, our `FakeDataSource` will implement the `ReminderDataSource` thus no need for the Repository class.
However, If you feel that you have to create a Repository, Please do fix the structure and implement it at your solution code.

**Comment by dariadobsai** [comment]
@mohamed-habib , You are right, it is possible to create a `FakeDataSource` with no problem.
However, for example if we want to create a `RemindersLocalRepositoryTest` we need to create  `RemindersLocalRepository` inside, but it requires the `RemindersDao` as a paramater and in this case, how it could be passed within the test class?

**Comment by mohamed-habib** [comment]
You can do that by using an in-memory database for testing.
The same way it was done in the course to create the `TasksLocalDataSource` inside `TasksLocalDataSourceTest`. Because as I said `RemindersLocalRepository` acts as the `LocalDataSource`.
Check: [TasksLocalDataSourceTest.kt](https://github.com/udacity/android-testing/blob/end_codelab_3/app/src/androidTest/java/com/example/android/architecture/blueprints/todoapp/data/source/local/TasksLocalDataSourceTest.kt#L63)

**Comment by SudKul** [comment]
Thanks, @mohamed-habib for helping us out here and @dariadobsai for a confirmation.
